# Generated by Django 3.2.3 on 2022-09-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_alter_comment_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='e_mail',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
