# Generated by Django 3.2.3 on 2022-10-14 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
